### ISSUE TITLE
JSON unexpected end of file error

### ISSUE THREAD

**Issue by nessamain** [JasonPad19/PowerBIScanner#1]
The file no longer works with the PowerBI Desktop edition October 2021 edition where the DataModelSchema seems to have been renamed. Even pointing to the new one throws a JSON unexpected end of file error. It is not possible for me to re-install PoweBI May edition as it no longer installs on my machine. Could you please make it work on PowerBI October 2021 edition?

**Comment by nessamain** [comment]
> 
> 
> The file no longer works with the PowerBI Desktop edition October 2021 edition where the DataModelSchema seems to have been renamed. Even pointing to the new one throws a JSON unexpected end of file error. It is not possible for me to re-install PoweBI May edition as it no longer installs on my machine. Could you please make it work on PowerBI October 2021 edition?

we have fixed it, sorry

**Comment by JasonPad19** [comment]
> > The file no longer works with the PowerBI Desktop edition October 2021 edition where the DataModelSchema seems to have been renamed. Even pointing to the new one throws a JSON unexpected end of file error. It is not possible for me to re-install PoweBI May edition as it no longer installs on my machine. Could you please make it work on PowerBI October 2021 edition?
> 
> we have fixed it, sorry

Awesome!! Would you like to share and upload the fixed version for the community please?

At the moment, I am testing out the admin API version so that we can retrieve metadata from power bi services. Can share more once I finish.

Thanks,
Jason
